version: "3"
services:
  node-app:
    container_name: node-app
    restart: always
    build: .
    ports:
      - "80:3000"
    links:
      - mongo
    environment:
      - PORT=3000
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db

volumes:
  data: